import Lollipop.Theorem_1_1.Statement
import Lollipop.Proposition_2_1.Statement
import Lollipop.Lemma_3_1.Statement
import Lollipop.Lemma_3_2.Statement
import Lollipop.Proposition_3_3.Statement
import Lollipop.Lemma_3_4.Statement
import Lollipop.Lemma_3_5.Statement
import Lollipop.Theorem_4_1.Statement
import Lollipop.Lemma_5_1.Statement
import Lollipop.Lemma_6_1.Statement
import Lollipop.Lemma_6_2.Statement
import Lollipop.Theorem_7_1.Statement
import Lollipop.Lemma_7_2.Statement
import Lollipop.Lemma_7_3.Statement
import Lollipop.Proposition_8_1.Statement
import Lollipop.Lemma_8_2.Statement
import Lollipop.Lemma_8_3.Statement
import Lollipop.Lemma_8_4.Statement
import Lollipop.Lemma_8_5.Statement
