#!/usr/bin/env python3
"""Run every ancillary verification and confirm the appendix certificate.

This script invokes the three reproducibility checkers and then checks that all
66 signs and exact fractions in the manuscript appendix agree with the CSV
certificate regenerated by ``certify_rational_base.py``.
"""
from __future__ import annotations

import csv
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def run(script: str) -> None:
    subprocess.run([sys.executable, str(ROOT / "scripts" / script)], check=True)


def manuscript_label(label: str) -> str:
    if label.startswith("I^-"):
        return "circle_circle.inner_margin"
    if label.startswith("I^+"):
        return "circle_circle.outer_margin"
    for symbol, suffix in (
        (r"\\Delta", "line_discriminant"),
        ("A", "anchor_power"),
        ("T", "vertex_ahead"),
    ):
        match = re.fullmatch(symbol + r"_\{?(\d)(\d)\}?", label)
        if match:
            i, j = match.groups()
            return f"ray_Q{i}_circle_Q{j}.{suffix}"
    if re.fullmatch(r"D_\{?\d\d\}?", label):
        return "ray_ray.direction_determinant"
    match = re.fullmatch(r"U_\{?(\d)\}?", label)
    if match:
        return f"ray_ray.Q{match.group(1)}_parameter_minus_radius"
    raise ValueError(f"Unrecognized appendix label: {label}")


def check_appendix() -> int:
    tex_path = ROOT / "manuscript" / "lollipop_formula.tex"
    csv_path = ROOT / "verification" / "rational_base_exact_sign_table.csv"
    tex = tex_path.read_text()
    pattern = re.compile(
        r"Q(\d)--Q(\d) & \$(.*?)\$ & \$([+-])\$ & "
        r"\\texttt\{([^}]+)\} \\\\"
    )
    manuscript_rows: dict[tuple[str, str], tuple[str, str]] = {}
    for i, j, label, sign, value in pattern.findall(tex):
        key = (f"Q{i}-Q{j}", manuscript_label(label))
        if key in manuscript_rows:
            raise AssertionError(f"Duplicate appendix row: {key}")
        manuscript_rows[key] = (sign, value)

    with csv_path.open(newline="") as handle:
        certificate_rows = list(csv.DictReader(handle))

    expected = {
        (row["pair"], row["test"]): (row["required_sign"], row["exact_value"])
        for row in certificate_rows
    }
    if manuscript_rows != expected:
        missing = sorted(set(expected) - set(manuscript_rows))
        extra = sorted(set(manuscript_rows) - set(expected))
        mismatched = sorted(
            key
            for key in set(expected) & set(manuscript_rows)
            if expected[key] != manuscript_rows[key]
        )
        raise AssertionError(
            f"Appendix certificate mismatch: missing={missing}, extra={extra}, "
            f"mismatched={mismatched}"
        )
    return len(expected)


def main() -> None:
    for script in (
        "certify_rational_base.py",
        "verify_local_family.py",
        "verify_closed_form.py",
    ):
        run(script)
    rows = check_appendix()
    print(f"Appendix-to-CSV comparison: {rows} exact rows matched.")
    print("ALL CHECKS PASSED")


if __name__ == "__main__":
    main()
