import Lollipop.Internal.ColoredTuran.WeightedTuran
import Lollipop.Internal.SectionFive.SupportDescent
import Lollipop.Internal.MatrixAssembly.Proof

/-!
End-to-end Theorem 1 certificates with the partition-intersection step
internalized.

The upper-bound certificate now carries the weighted quotient vertices, the
two blocker relations, and the two partitions used in the blocker lemma.
Lean builds the `3 x 4` intersection matrix, proves its total mass, proves
`Q <= entrySq` from the square-sum grouping lemma, and derives the blocker
lower bounds from weighted-Turan-style complement bounds.  The remaining
certificate fields are exactly the external production steps: colored Zykov,
weighted Turan complement bounds, geometric pair bounds, and lower
realizations.
-/

namespace Lollipop
namespace TheoremOneEndToEnd

open BigOperators

universe u

/-- A quotient certificate whose Section 4 blocker matrix is generated from
two actual partitions of a finite weighted quotient vertex set. -/
structure PartitionMatrixCertifiedQuotient
    (Vertex : Type u) [Fintype Vertex] [DecidableEq Vertex]
    extends QuotientData where
  nNat : Nat
  n_eq : n = (nNat : Rat)
  x : Vertex → Nat
  p3 : Vertex → Fin 3
  p4 : Vertex → Fin 4
  total_weight : totalWeightNat x = nNat
  Q_eq : Q = weightSquareSumRat x
  A : Vertex → Vertex → Prop
  B : Vertex → Vertex → Prop
  [decidable_A : DecidableRel A]
  [decidable_B : DecidableRel B]
  A_loopless : ∀ v, ¬ A v v
  B_loopless : ∀ v, ¬ B v v
  aOnlyE_eq : aOnlyE = weightedEdgeMass x A
  bOnlyD_eq : bOnlyD = weightedEdgeMass x B
  A_complement_le_p3 :
    orderedRelWeight x (fun v w : Vertex => v ≠ w ∧ ¬ A v w) ≤
      (totalWeightNat x : Rat)^2 - partitionSquareWeight x p3
  B_complement_le_p4 :
    orderedRelWeight x (fun v w : Vertex => v ≠ w ∧ ¬ B v w) ≤
      (totalWeightNat x : Rat)^2 - partitionSquareWeight x p4
  sigma_eq :
    sigma =
      3 * weightedEdgeMass x (fun v w : Vertex => v ≠ w) -
        2 * weightedEdgeMass x A - 2 * weightedEdgeMass x B

/-- The quotient objective identity follows from the concrete weighted
relations carried by the refined quotient certificate. -/
theorem PartitionMatrixCertifiedQuotient.quotient_identity
    {Vertex : Type u} [Fintype Vertex] [DecidableEq Vertex]
    (q : PartitionMatrixCertifiedQuotient Vertex) :
    QuotientIdentity q.toQuotientData := by
  letI : DecidableRel q.A := q.decidable_A
  letI : DecidableRel q.B := q.decidable_B
  let P := weightedEdgeMass q.x (fun v w : Vertex => v ≠ w)
  have hn : (totalWeightNat q.x : Rat) = q.n := by
    rw [q.total_weight, ← q.n_eq]
  have hP : P = (q.n^2 - q.Q) / 2 := by
    unfold P weightedEdgeMass
    rw [orderedRelWeight_offDiag, hn, q.Q_eq]
  have hsigma :
      q.sigma = 3 * P - 2 * q.aOnlyE - 2 * q.bOnlyD := by
    unfold P
    rw [q.sigma_eq, q.aOnlyE_eq, q.bOnlyD_eq]
  exact quotient_identity_from_cross_mass hP hsigma

/-- Convert a partition-generated quotient into the integral matrix quotient
used by the previous Theorem 1 dependency layer. -/
def PartitionMatrixCertifiedQuotient.toNatMatrixCertifiedQuotient
    {Vertex : Type u} [Fintype Vertex] [DecidableEq Vertex]
    (q : PartitionMatrixCertifiedQuotient Vertex) :
    TheoremOneFormal.NatMatrixCertifiedQuotient where
  n := q.n
  Q := q.Q
  aOnlyE := q.aOnlyE
  bOnlyD := q.bOnlyD
  sigma := q.sigma
  nNat := q.nNat
  n_eq := q.n_eq
  U := partitionMatrixNat q.x q.p3 q.p4
  matrix_total := by
    rw [matrixTotalNat_partitionMatrixNat, q.total_weight]
  a_lower := by
    letI : DecidableRel q.A := q.decidable_A
    have h :=
      weightedEdgeMass_ge_of_complement_le_partition
        q.x q.A q.p3 q.A_loopless q.A_complement_le_p3
    rw [q.aOnlyE_eq]
    rw [partitionSquareWeight_fin3_eq_rowSq_partitionMatrixNat q.x q.p3 q.p4] at h
    rw [q.Q_eq]
    exact h
  b_lower := by
    letI : DecidableRel q.B := q.decidable_B
    have h :=
      weightedEdgeMass_ge_of_complement_le_partition
        q.x q.B q.p4 q.B_loopless q.B_complement_le_p4
    rw [q.bOnlyD_eq]
    rw [partitionSquareWeight_fin4_eq_colSq_partitionMatrixNat q.x q.p3 q.p4] at h
    rw [q.Q_eq]
    exact h
  Q_le_entrySq := by
    rw [q.Q_eq]
    exact weightSquareSumRat_le_entrySqNat_partitionMatrixNat q.x q.p3 q.p4

@[simp]
theorem PartitionMatrixCertifiedQuotient.toNat_toQuotientData
    {Vertex : Type u} [Fintype Vertex] [DecidableEq Vertex]
    (q : PartitionMatrixCertifiedQuotient Vertex) :
    q.toNatMatrixCertifiedQuotient.toQuotientData = q.toQuotientData := by
  rfl

/-- Colored-pair certificate whose quotient matrix is generated by
intersecting the two weighted Turan partitions. -/
structure PartitionMatrixCertifiedColoredPair where
  nNat : Nat
  sigma : Rat
  Vertex : Type u
  [vertex_fintype : Fintype Vertex]
  [vertex_decidableEq : DecidableEq Vertex]
  quotient : PartitionMatrixCertifiedQuotient Vertex
  quotient_nNat : quotient.nNat = nNat
  quotient_preserves_sigma : quotient.sigma ≥ sigma

/-- Forget the partition witnesses after Lean has constructed the matrix
certificate from them. -/
def PartitionMatrixCertifiedColoredPair.toNatMatrixCertifiedColoredPair
    (p : PartitionMatrixCertifiedColoredPair.{u}) :
    TheoremOneFormal.NatMatrixCertifiedColoredPair := by
  letI : Fintype p.Vertex := p.vertex_fintype
  letI : DecidableEq p.Vertex := p.vertex_decidableEq
  exact
    { nNat := p.nNat
      sigma := p.sigma
      quotient := p.quotient.toNatMatrixCertifiedQuotient
      quotient_identity := by
        exact p.quotient.quotient_identity
      quotient_nNat := p.quotient_nNat
      quotient_preserves_sigma := p.quotient_preserves_sigma }

/-- Colored Turan bound with the matrix theorem and partition-intersection
algebra fully discharged. -/
theorem partition_matrix_certified_colored_turan_bound
    (p : PartitionMatrixCertifiedColoredPair.{u}) :
    p.sigma ≤ concreteS p.nNat := by
  exact TheoremOneFormal.nat_matrix_certified_colored_turan_bound
    matrix_theorem_proven p.toNatMatrixCertifiedColoredPair

/-- Pairwise lollipop upper certificate using partition-generated quotient
matrices. -/
structure PairwisePartitionMatrixCertifiedLollipopUpper where
  nNat : Nat
  crossings : Rat
  regions : Rat
  cross : Fin nNat → Fin nNat → Rat
  score : Fin nNat → Fin nNat → Rat
  pair : PartitionMatrixCertifiedColoredPair.{u}
  pair_nNat : pair.nNat = nNat
  crossings_le_pairSum : crossings ≤ pairSum nNat cross
  pointwise_crossing_bound :
    ∀ i j : Fin nNat, i < j → cross i j ≤ 4 + score i j
  score_sum_le_sigma : pairSum nNat score ≤ pair.sigma
  regions_eq : regions = crossings + (nNat : Rat) + 1

/-- Forget partition witnesses and produce the previous integral-matrix upper
certificate. -/
def PairwisePartitionMatrixCertifiedLollipopUpper.toPairwiseNatMatrixCertifiedLollipopUpper
    (L : PairwisePartitionMatrixCertifiedLollipopUpper.{u}) :
    TheoremOneFormal.PairwiseNatMatrixCertifiedLollipopUpper where
  nNat := L.nNat
  crossings := L.crossings
  regions := L.regions
  cross := L.cross
  score := L.score
  pair := L.pair.toNatMatrixCertifiedColoredPair
  pair_nNat := L.pair_nNat
  crossings_le_pairSum := L.crossings_le_pairSum
  pointwise_crossing_bound := L.pointwise_crossing_bound
  score_sum_le_sigma := L.score_sum_le_sigma
  regions_eq := L.regions_eq

/-- End-to-end upper bound for one arrangement from partition-generated
certificates. -/
theorem pairwise_partition_matrix_certified_lollipop_upper_bound_choose
    (L : PairwisePartitionMatrixCertifiedLollipopUpper.{u}) :
    L.regions ≤ candidateRegionsChoose L.nNat := by
  exact TheoremOneFormal.pairwise_nat_matrix_certified_lollipop_upper_bound_choose
    matrix_theorem_proven L.toPairwiseNatMatrixCertifiedLollipopUpper

/-- Upper certificates for every arrangement, with the blocker partition
intersection represented by concrete finite data. -/
def PairwisePartitionMatrixUpperCertificates
    (P : TheoremOne.ProblemFamily.{u}) : Prop :=
  ∀ n : Nat, ∀ A : P.Arrangement n,
    ∃ L : PairwisePartitionMatrixCertifiedLollipopUpper.{u},
      L.nNat = n ∧ L.regions = P.region n A

/-- Convert the refined upper-certificate family into the earlier certificate
shape. -/
theorem pairwise_partition_matrix_upper_certificates_to_nat_matrix
    {P : TheoremOne.ProblemFamily.{u}}
    (hupper : PairwisePartitionMatrixUpperCertificates P) :
    TheoremOneFormal.PairwiseNatMatrixUpperCertificates P := by
  intro n A
  rcases hupper n A with ⟨L, hLn, hLreg⟩
  exact ⟨L.toPairwiseNatMatrixCertifiedLollipopUpper, hLn, hLreg⟩

/-- Upper-bound half of Theorem 1 from refined partition-matrix
certificates. -/
theorem upper_bound_of_pairwise_partition_matrix_certificates
    (P : TheoremOne.ProblemFamily.{u})
    (hupper : PairwisePartitionMatrixUpperCertificates P) :
    ∀ n : Nat, ∀ A : P.Arrangement n,
      P.region n A ≤ candidateRegionsChoose n := by
  exact TheoremOneFormal.upper_bound_of_pairwise_nat_matrix_certificates P
    matrix_theorem_proven
    (pairwise_partition_matrix_upper_certificates_to_nat_matrix hupper)

end TheoremOneEndToEnd
end Lollipop
